# Specify base image
FROM node:18-alpine

# Create a working directory
WORKDIR /usr/app

#Copy package.json into container
COPY package.json ./

#Install dependencies
RUN npm install

#Copy other files into container
COPY ./ ./

#startup command
CMD ["npm", "start","serve"]
